#region Generated by `terra/node/src/rtc/impl/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc 
{
    public partial class BaseSpatialAudioEngineImpl
    {

        public void Release ()
        {
            _param.Clear();

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_RELEASE,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ?  :(void)AgoraJson.JsonToStruct<void>(_apiParam.Result, "result");


            return result;
        }
        
        public int SetMaxAudioRecvCount (int maxCount)
        {
            _param.Clear();
            _param.Add("maxCount", maxCount);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_SETMAXAUDIORECVCOUNT_46f8ab7,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int SetAudioRecvRange (float range)
        {
            _param.Clear();
            _param.Add("range", range);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_SETAUDIORECVRANGE_685e803,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int SetDistanceUnit (float unit)
        {
            _param.Clear();
            _param.Add("unit", unit);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_SETDISTANCEUNIT_685e803,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int UpdateSelfPosition (float[] position, float[] axisForward, float[] axisRight, float[] axisUp)
        {
            _param.Clear();
            _param.Add("position", position);
_param.Add("axisForward", axisForward);
_param.Add("axisRight", axisRight);
_param.Add("axisUp", axisUp);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_UPDATESELFPOSITION_2487f19,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int UpdateSelfPositionEx (float[] position, float[] axisForward, float[] axisRight, float[] axisUp, RtcConnection connection)
        {
            _param.Clear();
            _param.Add("position", position);
_param.Add("axisForward", axisForward);
_param.Add("axisRight", axisRight);
_param.Add("axisUp", axisUp);
_param.Add("connection", connection);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_UPDATESELFPOSITIONEX_564d6f9,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int UpdatePlayerPositionInfo (int playerId, RemoteVoicePositionInfo positionInfo)
        {
            _param.Clear();
            _param.Add("playerId", playerId);
_param.Add("positionInfo", positionInfo);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_UPDATEPLAYERPOSITIONINFO_b37c59d,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int SetParameters (string @params)
        {
            _param.Clear();
            _param.Add("params", @params);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_SETPARAMETERS_3a2037f,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int MuteLocalAudioStream (bool mute)
        {
            _param.Clear();
            _param.Add("mute", mute);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_MUTELOCALAUDIOSTREAM_5039d15,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int MuteAllRemoteAudioStreams (bool mute)
        {
            _param.Clear();
            _param.Add("mute", mute);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_MUTEALLREMOTEAUDIOSTREAMS_5039d15,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int SetZones (SpatialAudioZone const* zones, uint zoneCount)
        {
            _param.Clear();
            _param.Add("zones", zones);
_param.Add("zoneCount", zoneCount);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_SETZONES_414a27e,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int SetPlayerAttenuation (int playerId, double attenuation, bool forceSet)
        {
            _param.Clear();
            _param.Add("playerId", playerId);
_param.Add("attenuation", attenuation);
_param.Add("forceSet", forceSet);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_SETPLAYERATTENUATION_a15bc51,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
        public int MuteRemoteAudioStream (uint uid, bool mute)
        {
            _param.Clear();
            _param.Add("uid", uid);
_param.Add("mute", mute);

            var json = AgoraJson.ToJson(_param);
            var nRet = AgoraRtcNative.CallIrisApiWithArgs(_irisApiEngine, AgoraApiType.IBASESPATIALAUDIOENGINE_MUTEREMOTEAUDIOSTREAM_dbdc15a,
                json, (UInt32)json.Length,
                IntPtr.Zero, 0,
                ref _apiParam);

            var result = nRet != 0 ? nRet :(int)AgoraJson.GetData<int>(_apiParam.Result, "result");


            return result;
        }
        
    }
}