parsers:
  # CXXParser should always put first
  - name: CXXParser
    package: '@agoraio-extensions/cxx-parser'
    args:
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.2.5/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.2.5/include/*.h'
        exclude:
          - ''
      customHeaders:
        - ''
