#region Generated by `terra/node/src/rtc/ut/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

using NUnit.Framework;
using Agora.Rtc;
using System;
using view_t = System.UInt64;
namespace Agora.Rtc.Ut
{
    public partial class UnitTest_IVideoEffectObject
    {
        [Test]
        public void Test_AddOrUpdateVideoEffect_303a98c()
        {
            var nodeId = ParamsHelper.CreateParam<uint>();

            var templateName = ParamsHelper.CreateParam<string>();

            var nRet = @interface.AddOrUpdateVideoEffect(nodeId, templateName);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_RemoveVideoEffect_b48de50()
        {
            var nodeId = ParamsHelper.CreateParam<uint>();

            var nRet = @interface.RemoveVideoEffect(nodeId);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_PerformVideoEffectAction_eddb1a6()
        {
            var nodeId = ParamsHelper.CreateParam<uint>();

            var actionId = ParamsHelper.CreateParam<VIDEO_EFFECT_ACTION>();

            var nRet = @interface.PerformVideoEffectAction(nodeId, actionId);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_SetVideoEffectStringParam_0e4f59e()
        {
            var option = ParamsHelper.CreateParam<string>();

            var key = ParamsHelper.CreateParam<string>();

            var param = ParamsHelper.CreateParam<string>();

            var nRet = @interface.SetVideoEffectStringParam(option, key, param);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_SetVideoEffectFloatParam_e8dfcf8()
        {
            var option = ParamsHelper.CreateParam<string>();

            var key = ParamsHelper.CreateParam<string>();

            var param = ParamsHelper.CreateParam<float>();

            var nRet = @interface.SetVideoEffectFloatParam(option, key, param);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_SetVideoEffectIntParam_3b77680()
        {
            var option = ParamsHelper.CreateParam<string>();

            var key = ParamsHelper.CreateParam<string>();

            var param = ParamsHelper.CreateParam<int>();

            var nRet = @interface.SetVideoEffectIntParam(option, key, param);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_SetVideoEffectBoolParam_918930f()
        {
            var option = ParamsHelper.CreateParam<string>();

            var key = ParamsHelper.CreateParam<string>();

            var param = ParamsHelper.CreateParam<bool>();

            var nRet = @interface.SetVideoEffectBoolParam(option, key, param);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetVideoEffectFloatParam_ccad422()
        {
            var option = ParamsHelper.CreateParam<string>();

            var key = ParamsHelper.CreateParam<string>();

            var nRet = @interface.GetVideoEffectFloatParam(option, key);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetVideoEffectIntParam_ccad422()
        {
            var option = ParamsHelper.CreateParam<string>();

            var key = ParamsHelper.CreateParam<string>();

            var nRet = @interface.GetVideoEffectIntParam(option, key);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetVideoEffectBoolParam_ccad422()
        {
            var option = ParamsHelper.CreateParam<string>();

            var key = ParamsHelper.CreateParam<string>();

            var nRet = @interface.GetVideoEffectBoolParam(option, key);
            Assert.AreEqual(true, nRet);
        }


    }
}