#region Generated by `terra/node/src/rtc/ut/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

using NUnit.Framework;
using Agora.Rtc;
using System;
using view_t = System.UInt64;
namespace Agora.Rtc.Ut
{
    public partial class UnitTest_IMusicContentCenter
    {
        [Test]
        public void Test_Initialize_df70304()
        {
            var configuration = ParamsHelper.CreateParam<MusicContentCenterConfiguration>();

            var nRet = @interface.Initialize(configuration);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_AddVendor_db3598d()
        {
            var vendorId = ParamsHelper.CreateParam<MusicContentCenterVendorID>();

            var jsonVendorConfig = ParamsHelper.CreateParam<string>();

            var nRet = @interface.AddVendor(vendorId, jsonVendorConfig);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_RemoveVendor_387dbf0()
        {
            var vendorId = ParamsHelper.CreateParam<MusicContentCenterVendorID>();

            var nRet = @interface.RemoveVendor(vendorId);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_RenewToken_db3598d()
        {
            var vendorID = ParamsHelper.CreateParam<MusicContentCenterVendorID>();

            var token = ParamsHelper.CreateParam<string>();

            var nRet = @interface.RenewToken(vendorID, token);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_UnregisterEventHandler_ae49451()
        {
            var nRet = @interface.UnregisterEventHandler();
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetMusicCharts_66d4ecd()
        {
            var requestId = ParamsHelper.CreateParam<string>();

            var nRet = @interface.GetMusicCharts(ref requestId);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetMusicCollectionByMusicChartId_8cd0b4d()
        {
            var requestId = ParamsHelper.CreateParam<string>();

            var musicChartId = ParamsHelper.CreateParam<int>();

            var page = ParamsHelper.CreateParam<int>();

            var pageSize = ParamsHelper.CreateParam<int>();

            var jsonOption = ParamsHelper.CreateParam<string>();

            var nRet = @interface.GetMusicCollectionByMusicChartId(ref requestId, musicChartId, page, pageSize, jsonOption);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_SearchMusic_3f8cf09()
        {
            var requestId = ParamsHelper.CreateParam<string>();

            var keyWord = ParamsHelper.CreateParam<string>();

            var page = ParamsHelper.CreateParam<int>();

            var pageSize = ParamsHelper.CreateParam<int>();

            var jsonOption = ParamsHelper.CreateParam<string>();

            var nRet = @interface.SearchMusic(ref requestId, keyWord, page, pageSize, jsonOption);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_Preload_d3baeab()
        {
            var requestId = ParamsHelper.CreateParam<string>();

            var internalSongCode = ParamsHelper.CreateParam<long>();

            var nRet = @interface.Preload(ref requestId, internalSongCode);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_UnregisterScoreEventHandler_0932be1()
        {
            var nRet = @interface.UnregisterScoreEventHandler();
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_SetScoreLevel_fef2f2f()
        {
            var level = ParamsHelper.CreateParam<ScoreLevel>();

            var nRet = @interface.SetScoreLevel(level);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_StartScore_f631116()
        {
            var internalSongCode = ParamsHelper.CreateParam<long>();

            var nRet = @interface.StartScore(internalSongCode);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_StopScore()
        {
            var nRet = @interface.StopScore();
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_PauseScore()
        {
            var nRet = @interface.PauseScore();
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_ResumeScore()
        {
            var nRet = @interface.ResumeScore();
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetCumulativeScoreData_c8fad3d()
        {
            var cumulativeScoreData = ParamsHelper.CreateParam<CumulativeScoreData>();

            var nRet = @interface.GetCumulativeScoreData(ref cumulativeScoreData);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_RemoveCache_f631116()
        {
            var internalSongCode = ParamsHelper.CreateParam<long>();

            var nRet = @interface.RemoveCache(internalSongCode);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetCaches_c4f9978()
        {
            var cacheInfo = ParamsHelper.CreateParam<MusicCacheInfo[]>();

            var cacheInfoSize = ParamsHelper.CreateParam<int>();

            var nRet = @interface.GetCaches(ref cacheInfo, ref cacheInfoSize);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_IsPreloaded_f631116()
        {
            var internalSongCode = ParamsHelper.CreateParam<long>();

            var nRet = @interface.IsPreloaded(internalSongCode);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetLyric_5ab5efd()
        {
            var requestId = ParamsHelper.CreateParam<string>();

            var internalSongCode = ParamsHelper.CreateParam<long>();

            var lyricType = ParamsHelper.CreateParam<int>();

            var nRet = @interface.GetLyric(ref requestId, internalSongCode, lyricType);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetLyricInfo_d3baeab()
        {
            var requestId = ParamsHelper.CreateParam<string>();

            var internalSongCode = ParamsHelper.CreateParam<long>();

            var nRet = @interface.GetLyricInfo(ref requestId, internalSongCode);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetSongSimpleInfo_d3baeab()
        {
            var requestId = ParamsHelper.CreateParam<string>();

            var internalSongCode = ParamsHelper.CreateParam<long>();

            var nRet = @interface.GetSongSimpleInfo(ref requestId, internalSongCode);
            Assert.AreEqual(0, nRet);
        }


        [Test]
        public void Test_GetInternalSongCode_d71d94d()
        {
            var vendorId = ParamsHelper.CreateParam<MusicContentCenterVendorID>();

            var songCode = ParamsHelper.CreateParam<string>();

            var jsonOption = ParamsHelper.CreateParam<string>();

            var internalSongCode = ParamsHelper.CreateParam<long>();

            var nRet = @interface.GetInternalSongCode(vendorId, songCode, jsonOption, ref internalSongCode);
            Assert.AreEqual(0, nRet);
        }


    }
}