#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc
{
    public partial class MediaRecorderObserver : IMediaRecorderObserver
    {
        public event Action<string, uint, RecorderState, RecorderReasonCode> EventOnRecorderStateChanged;

        public override void OnRecorderStateChanged(string channelId, uint uid, RecorderState state, RecorderReasonCode reason)
        {
            if (EventOnRecorderStateChanged == null) return;
            EventOnRecorderStateChanged.Invoke(channelId, uid, state, reason);
        }

        public event Action<string, uint, RecorderInfo> EventOnRecorderInfoUpdated;

        public override void OnRecorderInfoUpdated(string channelId, uint uid, RecorderInfo info)
        {
            if (EventOnRecorderInfoUpdated == null) return;
            EventOnRecorderInfoUpdated.Invoke(channelId, uid, info);
        }

    }
}