#region Generated by `terra/node/src/rtc/struct_enumz/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

using System;
using Agora.Rtc.LitJson;
using view_t = System.UInt64;
using uint8_t = System.Byte;
using int16_t = System.Int16;

namespace Agora.Rtc
{
    ///
    /// <summary>
    /// Virtual metronome state.
    /// </summary>
    ///
    public enum RHYTHM_PLAYER_STATE_TYPE
    {
        ///
        /// <summary>
        /// 810: The virtual metronome is not started or has been stopped.
        /// </summary>
        ///
        RHYTHM_PLAYER_STATE_IDLE = 810,

        ///
        /// <summary>
        /// 811: Opening the metronome audio file.
        /// </summary>
        ///
        RHYTHM_PLAYER_STATE_OPENING,

        ///
        /// <summary>
        /// 812: Decoding the metronome audio file.
        /// </summary>
        ///
        RHYTHM_PLAYER_STATE_DECODING,

        ///
        /// <summary>
        /// 813: Playing the metronome audio file.
        /// </summary>
        ///
        RHYTHM_PLAYER_STATE_PLAYING,

        ///
        /// <summary>
        /// 814: Failed to start the virtual metronome. You can troubleshoot the issue using the reported error code errorCode, or try starting the virtual metronome again.
        /// </summary>
        ///
        RHYTHM_PLAYER_STATE_FAILED,

    }

    ///
    /// <summary>
    /// Virtual metronome error information.
    /// </summary>
    ///
    public enum RHYTHM_PLAYER_REASON
    {
        ///
        /// <summary>
        /// 0: The metronome audio file is playing normally without errors.
        /// </summary>
        ///
        RHYTHM_PLAYER_REASON_OK = 0,

        ///
        /// <summary>
        /// 1: General error with no specific cause.
        /// </summary>
        ///
        RHYTHM_PLAYER_REASON_FAILED = 1,

        ///
        /// <summary>
        /// 801: Error opening the metronome audio file.
        /// </summary>
        ///
        RHYTHM_PLAYER_REASON_CAN_NOT_OPEN = 801,

        ///
        /// <summary>
        /// 802: Error playing the metronome audio file.
        /// </summary>
        ///
        RHYTHM_PLAYER_REASON_CAN_NOT_PLAY,

        ///
        /// <summary>
        /// 803: The duration of the metronome audio file exceeds the limit. The maximum duration is 1.2 seconds.
        /// </summary>
        ///
        RHYTHM_PLAYER_REASON_FILE_OVER_DURATION_LIMIT,

    }

    ///
    /// <summary>
    /// Virtual metronome configuration.
    /// </summary>
    ///
    public class AgoraRhythmPlayerConfig
    {
        ///
        /// <summary>
        /// Number of beats per measure, range [1,9]. Default is 4, which means 1 strong beat and 3 weak beats per measure.
        /// </summary>
        ///
        public int beatsPerMeasure;

        ///
        /// <summary>
        /// Tempo (beats per minute), range [60,360]. Default is 60, meaning 60 beats per minute.
        /// </summary>
        ///
        public int beatsPerMinute;

        public AgoraRhythmPlayerConfig()
        {
            this.beatsPerMeasure = 4;
            this.beatsPerMinute = 60;
        }

        public AgoraRhythmPlayerConfig(int beatsPerMeasure, int beatsPerMinute)
        {
            this.beatsPerMeasure = beatsPerMeasure;
            this.beatsPerMinute = beatsPerMinute;
        }
    }

}
