#region Generated by `terra/node/src/rtc/struct_enumz/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

using System;
using Agora.Rtc.LitJson;
using view_t = System.UInt64;
using uint8_t = System.Byte;
using int16_t = System.Int16;

namespace Agora.Rtc
{
    ///
    /// @ignore
    ///
    public enum H265_TRANSCODE_RESULT
    {
        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_UNKNOWN = -1,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_SUCCESS = 0,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_REQUEST_INVALID = 1,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_UNAUTHORIZED = 2,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_TOKEN_EXPIRED = 3,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_FORBIDDEN = 4,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_NOT_FOUND = 5,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_CONFLICTED = 6,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_NOT_SUPPORTED = 7,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_TOO_OFTEN = 8,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_SERVER_INTERNAL_ERROR = 9,

        ///
        /// @ignore
        ///
        H265_TRANSCODE_RESULT_SERVICE_UNAVAILABLE = 10,

    }

}
