#region Generated by `terra/node/src/rtc/struct_enumz/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

using System;
using Agora.Rtc.LitJson;
using view_t = System.UInt64;
using uint8_t = System.Byte;
using int16_t = System.Int16;

namespace Agora.Rtc
{
    ///
    /// <summary>
    /// Class that contains connection information.
    /// </summary>
    ///
    public class RtcConnection
    {
        ///
        /// <summary>
        /// Channel name.
        /// </summary>
        ///
        public string channelId;

        ///
        /// <summary>
        /// Local user ID.
        /// </summary>
        ///
        public uint localUid;

        public RtcConnection()
        {
            this.channelId = "";
            this.localUid = 0;
        }

        public RtcConnection(string channel_id, uint local_uid)
        {
            this.channelId = channel_id;
            this.localUid = local_uid;
        }

    }

}
