#region Generated by `terra/node/src/rtc/ut/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

using System;
using Agora.Rtc;
namespace Agora.Rtc.Ut
{
    public partial class UTFaceInfoObserver : IFaceInfoObserver
    {
        public bool OnFaceInfo_3a2037f_be_trigger = false;
        public string OnFaceInfo_3a2037f_outFaceInfo;

        public override bool OnFaceInfo(string outFaceInfo)
        {
            OnFaceInfo_3a2037f_be_trigger = true;
            OnFaceInfo_3a2037f_outFaceInfo = outFaceInfo;
            return true;
        }

        public bool OnFaceInfoPassed(string outFaceInfo)
        {
            if (OnFaceInfo_3a2037f_be_trigger == false)
                return false;

            if (ParamsHelper.Compare<string>(OnFaceInfo_3a2037f_outFaceInfo, outFaceInfo) == false)
                return false;

            return true;
        }

        /////////////////////////////////

    }
}