#region Generated by `terra/node/src/rtc/ut/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

using System;
using Agora.Rtc;
namespace Agora.Rtc.Ut
{
    public partial class UTH265TranscoderObserver : IH265TranscoderObserver
    {
        public bool OnEnableTranscode_6ba6646_be_trigger = false;
        public H265_TRANSCODE_RESULT OnEnableTranscode_6ba6646_result;

        public override void OnEnableTranscode(H265_TRANSCODE_RESULT result)
        {
            OnEnableTranscode_6ba6646_be_trigger = true;
            OnEnableTranscode_6ba6646_result = result;
        }

        public bool OnEnableTranscodePassed(H265_TRANSCODE_RESULT result)
        {
            if (OnEnableTranscode_6ba6646_be_trigger == false)
                return false;

            if (ParamsHelper.Compare<H265_TRANSCODE_RESULT>(OnEnableTranscode_6ba6646_result, result) == false)
                return false;

            return true;
        }

        /////////////////////////////////

        public bool OnQueryChannel_31ba3df_be_trigger = false;
        public H265_TRANSCODE_RESULT OnQueryChannel_31ba3df_result;
        public string OnQueryChannel_31ba3df_originChannel;
        public string OnQueryChannel_31ba3df_transcodeChannel;

        public override void OnQueryChannel(H265_TRANSCODE_RESULT result, string originChannel, string transcodeChannel)
        {
            OnQueryChannel_31ba3df_be_trigger = true;
            OnQueryChannel_31ba3df_result = result;
            OnQueryChannel_31ba3df_originChannel = originChannel;
            OnQueryChannel_31ba3df_transcodeChannel = transcodeChannel;
        }

        public bool OnQueryChannelPassed(H265_TRANSCODE_RESULT result, string originChannel, string transcodeChannel)
        {
            if (OnQueryChannel_31ba3df_be_trigger == false)
                return false;

            if (ParamsHelper.Compare<H265_TRANSCODE_RESULT>(OnQueryChannel_31ba3df_result, result) == false)
                return false;
            if (ParamsHelper.Compare<string>(OnQueryChannel_31ba3df_originChannel, originChannel) == false)
                return false;
            if (ParamsHelper.Compare<string>(OnQueryChannel_31ba3df_transcodeChannel, transcodeChannel) == false)
                return false;

            return true;
        }

        /////////////////////////////////

        public bool OnTriggerTranscode_6ba6646_be_trigger = false;
        public H265_TRANSCODE_RESULT OnTriggerTranscode_6ba6646_result;

        public override void OnTriggerTranscode(H265_TRANSCODE_RESULT result)
        {
            OnTriggerTranscode_6ba6646_be_trigger = true;
            OnTriggerTranscode_6ba6646_result = result;
        }

        public bool OnTriggerTranscodePassed(H265_TRANSCODE_RESULT result)
        {
            if (OnTriggerTranscode_6ba6646_be_trigger == false)
                return false;

            if (ParamsHelper.Compare<H265_TRANSCODE_RESULT>(OnTriggerTranscode_6ba6646_result, result) == false)
                return false;

            return true;
        }

        /////////////////////////////////

    }
}