#region Generated by `terra/node/src/rtc/ut/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

using System;
using Agora.Rtc;
namespace Agora.Rtc.Ut
{
    public partial class UTVideoEncodedFrameObserver : IVideoEncodedFrameObserver
    {
        public bool OnEncodedVideoFrameReceived_6922697_be_trigger = false;
        public uint OnEncodedVideoFrameReceived_6922697_uid;
        public IntPtr OnEncodedVideoFrameReceived_6922697_imageBuffer;
        public ulong OnEncodedVideoFrameReceived_6922697_length;
        public EncodedVideoFrameInfo OnEncodedVideoFrameReceived_6922697_videoEncodedFrameInfo;

        public override bool OnEncodedVideoFrameReceived(uint uid, IntPtr imageBuffer, ulong length, EncodedVideoFrameInfo videoEncodedFrameInfo)
        {
            OnEncodedVideoFrameReceived_6922697_be_trigger = true;
            OnEncodedVideoFrameReceived_6922697_uid = uid;
            OnEncodedVideoFrameReceived_6922697_imageBuffer = imageBuffer;
            OnEncodedVideoFrameReceived_6922697_length = length;
            OnEncodedVideoFrameReceived_6922697_videoEncodedFrameInfo = videoEncodedFrameInfo;
            return true;
        }

        public bool OnEncodedVideoFrameReceivedPassed(uint uid, IntPtr imageBuffer, ulong length, EncodedVideoFrameInfo videoEncodedFrameInfo)
        {
            if (OnEncodedVideoFrameReceived_6922697_be_trigger == false)
                return false;

            if (ParamsHelper.Compare<uint>(OnEncodedVideoFrameReceived_6922697_uid, uid) == false)
                return false;
            if (ParamsHelper.Compare<IntPtr>(OnEncodedVideoFrameReceived_6922697_imageBuffer, imageBuffer) == false)
                return false;
            if (ParamsHelper.Compare<ulong>(OnEncodedVideoFrameReceived_6922697_length, length) == false)
                return false;
            if (ParamsHelper.Compare<EncodedVideoFrameInfo>(OnEncodedVideoFrameReceived_6922697_videoEncodedFrameInfo, videoEncodedFrameInfo) == false)
                return false;

            return true;
        }

        /////////////////////////////////

    }
}