#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc
{
    ///
    /// <summary>
    /// Audio device management methods.
    /// </summary>
    ///
    public abstract class IAudioDeviceManager
    {
        ///
        /// <summary>
        /// Gets the list of all playback devices in the system.
        /// 
        /// (Windows and macOS only)
        /// </summary>
        ///
        /// <returns>
        /// If the method call succeeds, returns a DeviceInfo array containing the device ID and device name of all audio playback devices.
        /// If the method call fails: null.
        /// </returns>
        ///
        public abstract DeviceInfo[] EnumeratePlaybackDevices();

        ///
        /// <summary>
        /// Gets the list of all audio recording devices in the system.
        /// 
        /// (Windows and macOS only)
        /// </summary>
        ///
        /// <returns>
        /// If the method call succeeds, returns a DeviceInfo array containing the device ID and device name of all audio recording devices.
        /// If the method call fails: null.
        /// </returns>
        ///
        public abstract DeviceInfo[] EnumerateRecordingDevices();

        ///
        /// <summary>
        /// Gets the system default audio playback device.
        /// 
        /// (Windows and macOS only)
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The ID of the system default audio playback device. </param>
        ///
        /// <param name="deviceName"> Output parameter. The name of the system default audio playback device. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetPlaybackDefaultDevice(ref string deviceId, ref string deviceName);

        ///
        /// <summary>
        /// Gets the system default audio playback device and its type.
        /// 
        /// (macOS only)
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The ID of the system default audio playback device. </param>
        ///
        /// <param name="deviceName"> Output parameter. The name of the system default audio playback device. </param>
        ///
        /// <param name="deviceTypeName"> Output parameter. The type of the audio device, such as: built-in, USB, HDMI, etc. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetPlaybackDefaultDevice(ref string deviceId, ref string deviceTypeName, ref string deviceName);

        ///
        /// <summary>
        /// Retrieves the system default audio recording device.
        /// 
        /// (Windows and macOS only)
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The ID of the system default audio recording device. </param>
        ///
        /// <param name="deviceName"> Output parameter. The name of the system default audio recording device. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetRecordingDefaultDevice(ref string deviceId, ref string deviceName);

        ///
        /// <summary>
        /// Retrieves the system default audio recording device and its type.
        /// 
        /// (macOS only)
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The ID of the system default audio recording device. </param>
        ///
        /// <param name="deviceName"> Output parameter. The name of the system default audio recording device. </param>
        ///
        /// <param name="deviceTypeName"> Output parameter. The type of the audio device, such as built-in, USB, HDMI, etc. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetRecordingDefaultDevice(ref string deviceId, ref string deviceTypeName, ref string deviceName);

        ///
        /// <summary>
        /// Specifies the playback device.
        /// 
        /// This method changes the current audio route but does not change the system default audio route. For example, if the system default audio route is Speaker 1, and you call this method before joining a channel to set the audio route to Speaker 2, the SDK performs device testing on Speaker 2. After testing, when you join a channel, the SDK still uses the system default audio route, which is Speaker 1. This method applies to Windows and macOS only.
        /// </summary>
        ///
        /// <param name="deviceId"> Specifies the playback device. Obtained via EnumeratePlaybackDevices. Plugging or unplugging devices does not affect deviceId. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int SetPlaybackDevice(string deviceId);

        ///
        /// <summary>
        /// Gets the current audio playback device.
        /// 
        /// (Windows and macOS only)
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The device ID of the current audio playback device. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetPlaybackDevice(ref string deviceId);

        ///
        /// <summary>
        /// Retrieves information about the audio playback device.
        /// 
        /// (Windows and macOS only)
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The device ID of the playback device. </param>
        ///
        /// <param name="deviceName"> Output parameter. The device name of the playback device. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetPlaybackDeviceInfo(ref string deviceId, ref string deviceName);

        ///
        /// <summary>
        /// Retrieves information about the audio playback device and its type.
        /// 
        /// (macOS only)
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The device ID of the playback device. </param>
        ///
        /// <param name="deviceName"> Output parameter. The device name of the playback device. </param>
        ///
        /// <param name="deviceTypeName"> Output parameter. The type of the audio playback device, such as built-in, USB, HDMI, etc. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetPlaybackDeviceInfo(ref string deviceId, ref string deviceName, ref string deviceTypeName);

        ///
        /// <summary>
        /// Sets the playback device volume.
        /// 
        /// This method applies to Windows only.
        /// </summary>
        ///
        /// <param name="volume"> Playback device volume. Value range: [0,255]. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int SetPlaybackDeviceVolume(int volume);

        ///
        /// <summary>
        /// Retrieves the volume of the playback device.
        /// </summary>
        ///
        /// <returns>
        /// Playback device volume. Value range: [0,255].
        /// </returns>
        ///
        public abstract int GetPlaybackDeviceVolume(ref int volume);

        ///
        /// <summary>
        /// Specifies the recording device.
        /// 
        /// This method changes the current recording device used by the SDK but does not change the system default recording device. For example, if the system default recording device is Microphone 1, and you call this method before joining a channel to set the current audio route to Bluetooth Headset 1, the SDK performs device testing on Bluetooth Headset 1. After testing, when you join a channel, the SDK still uses the system default recording device, which is Microphone 1. This method applies to Windows and macOS only.
        /// </summary>
        ///
        /// <param name="deviceId"> Device ID of the recording device. You can obtain it via EnumerateRecordingDevices. Plugging or unplugging devices does not affect deviceId. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int SetRecordingDevice(string deviceId);

        ///
        /// <summary>
        /// Retrieves the current audio recording device.
        /// 
        /// (Windows and macOS only)
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The device ID of the current recording device. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetRecordingDevice(ref string deviceId);

        ///
        /// <summary>
        /// Retrieves information about the audio recording device.
        /// 
        /// (Windows and macOS only)
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The device ID of the playback device. </param>
        ///
        /// <param name="deviceName"> Output parameter. The device name of the playback device. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetRecordingDeviceInfo(ref string deviceId, ref string deviceName);

        ///
        /// <summary>
        /// Retrieves information about the audio recording device and its type.
        /// 
        /// (macOS only)
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The device ID of the playback device. </param>
        ///
        /// <param name="deviceName"> Output parameter. The device name of the playback device. </param>
        ///
        /// <param name="deviceTypeName"> Output parameter. The type of the audio recording device, such as built-in, USB, HDMI, etc. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetRecordingDeviceInfo(ref string deviceId, ref string deviceName, ref string deviceTypeName);

        ///
        /// <summary>
        /// Sets the volume of the audio recording device.
        /// 
        /// This method is only available on Windows and macOS.
        /// </summary>
        ///
        /// <param name="volume"> The volume of the audio recording device. The range is [0,255]. 0 means mute, and 255 means the maximum volume. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and troubleshooting.
        /// </returns>
        ///
        public abstract int SetRecordingDeviceVolume(int volume);

        ///
        /// <summary>
        /// Gets the volume of the recording device.
        /// 
        /// This method applies to Windows only.
        /// </summary>
        ///
        /// <returns>
        /// The volume of the recording device. Value range: [0,255].
        /// </returns>
        ///
        public abstract int GetRecordingDeviceVolume(ref int volume);

        ///
        /// <summary>
        /// Specifies the loopback device.
        /// 
        /// By default, the SDK uses the current playback device as the loopback device. To specify another audio device as the loopback device, call this method and set deviceId to the desired loopback device.
        /// This method changes the current recording device used by the SDK but does not change the system default recording device. For example, if the system default recording device is Microphone 1, and you call this method before joining a channel to set the current audio route to Soundcard 1, the SDK performs device testing on Soundcard 1. After testing, when you join a channel, the SDK still uses the system default recording device, which is Microphone 1. This method applies to Windows and macOS only.
        /// Applicable scenario:
        /// App A plays music through a Bluetooth headset; App B is used for video conferencing through a speaker.
        /// If the loopback device is set to the Bluetooth headset, the SDK publishes the music from App A to the remote end.
        /// If the loopback device is set to the speaker, the SDK does not publish the music from App A to the remote end.
        /// If you switch from Bluetooth headset to wired headset for App A after setting the loopback device to Bluetooth headset, you need to call this method again to set the loopback device to the wired headset. The SDK will then continue to publish the music from App A to the remote end.
        /// </summary>
        ///
        /// <param name="deviceId"> Specifies the loopback device used by the SDK. Obtained via EnumeratePlaybackDevices. Plugging or unplugging devices does not affect deviceId. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int SetLoopbackDevice(string deviceId);

        ///
        /// <summary>
        /// Gets the current loopback capture device.
        /// 
        /// This method is for Windows and macOS only.
        /// </summary>
        ///
        /// <param name="deviceId"> Output parameter. The ID of the current loopback capture device. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int GetLoopbackDevice(ref string deviceId);

        ///
        /// <summary>
        /// Sets the playback device to mute.
        /// </summary>
        ///
        /// <param name="mute"> Whether to mute the playback device: true : Mute the playback device. false : Do not mute the playback device. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int SetPlaybackDeviceMute(bool mute);

        ///
        /// @ignore
        ///
        public abstract int GetPlaybackDeviceMute(ref bool mute);

        ///
        /// <summary>
        /// Sets the current recording device to mute.
        /// </summary>
        ///
        /// <param name="mute"> Whether to mute the recording device: true : The recording device is muted. false : The recording device is not muted. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int SetRecordingDeviceMute(bool mute);

        ///
        /// <summary>
        /// Gets the mute status of the current recording device.
        /// </summary>
        ///
        /// <returns>
        /// true : The recording device is muted. false : The recording device is not muted.
        /// </returns>
        ///
        public abstract int GetRecordingDeviceMute(ref bool mute);

        ///
        /// <summary>
        /// Starts a playback device test.
        /// 
        /// This method tests whether the local playback device is working properly. After starting the test, the SDK plays the specified audio file. If the tester hears sound, the playback device is functioning properly.
        /// After calling this method, the SDK triggers the OnAudioVolumeIndication callback every 100 milliseconds to report the volume information of uid = 1 and the playback device.
        /// The difference between this method and StartEchoTest is that this method checks whether the local playback device is working, while the latter checks whether the audio/video devices and network are functioning properly. You must call this method before joining a channel. After the test is complete, if you want to join a channel, make sure to call StopPlaybackDeviceTest to stop the test first.
        /// </summary>
        ///
        /// <param name="testAudioFilePath">
        /// The absolute path of the audio file. The path string must be in UTF-8 encoding.
        /// Supported file formats: wav, mp3, m4a, aac.
        /// Supported sampling rates: 8000, 16000, 32000, 44100, 48000.
        /// </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and troubleshooting.
        /// </returns>
        ///
        public abstract int StartPlaybackDeviceTest(string testAudioFilePath);

        ///
        /// <summary>
        /// Stops the playback device test.
        /// 
        /// This method stops the playback device test. After calling StartPlaybackDeviceTest, you must call this method to stop the test. You must call this method before joining a channel.
        /// </summary>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and troubleshooting.
        /// </returns>
        ///
        public abstract int StopPlaybackDeviceTest();

        ///
        /// <summary>
        /// Starts a recording device test.
        /// 
        /// This method tests whether the local recording device is working properly. After calling this method, the SDK triggers the OnAudioVolumeIndication callback at the specified time interval to report the volume information of uid = 0 and the recording device.
        /// The difference between this method and StartEchoTest is that this method checks whether the local recording device is working, while the latter checks whether the audio/video devices and network are functioning properly. You must call this method before joining a channel. After the test is complete, if you want to join a channel, make sure to call StopRecordingDeviceTest to stop the test first.
        /// </summary>
        ///
        /// <param name="indicationInterval"> The time interval in milliseconds at which the SDK triggers the OnAudioVolumeIndication callback. The minimum value is 10. Otherwise, the OnAudioVolumeIndication callback will not be received and the SDK will return error code -2. Agora recommends setting this value to 100. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and troubleshooting.
        /// -2: Invalid parameter. Please reset the parameter.
        /// </returns>
        ///
        public abstract int StartRecordingDeviceTest(int indicationInterval);

        ///
        /// <summary>
        /// Stops the recording device test.
        /// 
        /// This method stops the recording device test. After calling StartRecordingDeviceTest, you must call this method to stop the test. You must call this method before joining a channel.
        /// </summary>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and troubleshooting.
        /// </returns>
        ///
        public abstract int StopRecordingDeviceTest();

        ///
        /// <summary>
        /// Starts an audio device loopback test.
        /// 
        /// This method tests whether the audio recording and playback devices are working properly. Once the test starts, the recording device captures local audio and plays it back through the playback device. The SDK triggers two OnAudioVolumeIndication callbacks at the specified time interval to report the volume levels of the recording device (uid = 0) and the playback device (uid = 1).
        /// This method is only available on Windows and macOS.
        /// You can call this method before or after joining a channel.
        /// Only the host role can call this method.
        /// This method only tests local audio devices and does not involve network connections.
        /// After the test is complete, you must call StopAudioDeviceLoopbackTest to stop the loopback test.
        /// </summary>
        ///
        /// <param name="indicationInterval"> The time interval in milliseconds at which the SDK triggers the OnAudioVolumeIndication callback. It is recommended to set this to more than 200 ms. If set to less than 10 ms, the OnAudioVolumeIndication callback will not be received. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and troubleshooting.
        /// </returns>
        ///
        public abstract int StartAudioDeviceLoopbackTest(int indicationInterval);

        ///
        /// <summary>
        /// Stops the audio device loopback test.
        /// 
        /// This method is only available on Windows and macOS.
        /// You can call this method before or after joining a channel.
        /// Only the host role can call this method.
        /// After calling StartAudioDeviceLoopbackTest, you must call this method to stop the loopback test.
        /// </summary>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and troubleshooting.
        /// </returns>
        ///
        public abstract int StopAudioDeviceLoopbackTest();

        ///
        /// <summary>
        /// Sets whether the audio playback device used by the SDK follows the system default audio playback device.
        /// 
        /// (Windows and macOS only)
        /// </summary>
        ///
        /// <param name="enable"> Whether to follow the system default audio playback device: true : Follow. When the system default audio playback device changes, the SDK immediately switches to it. false : Do not follow. The SDK switches to the system default audio playback device only when the current device used by the SDK is removed. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int FollowSystemPlaybackDevice(bool enable);

        ///
        /// <summary>
        /// Sets whether the audio recording device used by the SDK follows the system default audio recording device.
        /// 
        /// (Windows and macOS only)
        /// </summary>
        ///
        /// <param name="enable"> Whether to follow the system default audio recording device: true : Follow. When the system default audio recording device changes, the SDK immediately switches to it. false : Do not follow. The SDK switches to the system default audio recording device only when the current device used by the SDK is removed. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int FollowSystemRecordingDevice(bool enable);

        ///
        /// <summary>
        /// Sets whether the loopback capture device follows the system default playback device.
        /// 
        /// This method is only applicable to Windows and macOS.
        /// </summary>
        ///
        /// <param name="enable"> Whether to follow the system default playback device: true : Follow. When the system default playback device changes, the SDK immediately switches the loopback capture device accordingly. false : Do not follow. The SDK switches to the system default playback device only when the current loopback capture device is removed. </param>
        ///
        /// <returns>
        /// 0: Success.
        /// &lt; 0: Failure. See [Error Codes](https://docs.agora.io/en/video-calling/troubleshooting/error-codes) for details and resolution suggestions.
        /// </returns>
        ///
        public abstract int FollowSystemLoopbackDevice(bool enable);

    }
}