#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc {
    public abstract class IAudioPcmFrameSink 
    {
        public virtual void OnFrame (AudioPcmFrame frame)
        {
        }

    }
}