#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc
{
    ///
    /// @ignore
    ///
    public abstract class IH265TranscoderObserver
    {
        ///
        /// @ignore
        ///
        public abstract void OnEnableTranscode(H265_TRANSCODE_RESULT result);

        ///
        /// @ignore
        ///
        public abstract void OnQueryChannel(H265_TRANSCODE_RESULT result, string originChannel, string transcodeChannel);

        ///
        /// @ignore
        ///
        public abstract void OnTriggerTranscode(H265_TRANSCODE_RESULT result);

    }
}