#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc {
    public abstract class IMediaPlayerCustomDataProvider 
    {
        public virtual int OnReadData (IntPtr buffer, int bufferSize)
        {
            return 0;
        }

        public virtual long OnSeek (long offset, int whence)
        {
            return 0;
        }

    }
}