#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc
{
    ///
    /// <summary>
    /// Metadata observer.
    /// </summary>
    ///
    public abstract class IMetadataObserver
    {
        ///
        /// @ignore
        ///
#if !(UNITY_EDITOR_WIN || UNITY_EDITOR_OSX || UNITY_STANDALONE_WIN || UNITY_STANDALONE_OSX || UNITY_IOS || UNITY_ANDROID)
        public virtual int GetMaxMetadataSize()
        {
            return 0;
        }
#endif

        ///
        /// <summary>
        /// Occurs when the sender is ready to send metadata.
        /// 
        /// This callback is triggered when the SDK is ready to send metadata.
        /// </summary>
        ///
        /// <param name="source_Type"> The type of video data. See VIDEO_SOURCE_TYPE. </param>
        ///
        /// <param name="metadata"> The metadata the user wants to send. See Metadata. </param>
        ///
        /// <returns>
        /// true : Send false : Do not send
        /// </returns>
        ///
#if !(UNITY_EDITOR_WIN || UNITY_EDITOR_OSX || UNITY_STANDALONE_WIN || UNITY_STANDALONE_OSX || UNITY_IOS || UNITY_ANDROID)
        public virtual bool OnReadyToSendMetadata(ref Metadata metadata, VIDEO_SOURCE_TYPE source_type)
        {
            return true;
        }
#endif

        ///
        /// <summary>
        /// Occurs when metadata is received on the receiving end.
        /// </summary>
        ///
        /// <param name="metadata"> The received metadata. See Metadata. </param>
        ///
        public virtual void OnMetadataReceived(Metadata metadata)
        {
        }

    }
}