#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc {
    public abstract class IMusicPlayer  : IMediaPlayer 
    {
        public abstract int Open (long songCode, long startPos = 0);

        public abstract int SetPlayMode (MusicPlayMode mode);

    }
}