#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc {
    public abstract class IMusicContentCenterEventHandler 
    {
        public abstract void OnMusicChartsResult (string requestId, MusicChartInfo[] result, MusicContentCenterStatusCode errorCode);

        public abstract void OnMusicCollectionResult (string requestId, MusicCollection result, MusicContentCenterStatusCode errorCode);

        public abstract void OnLyricResult (string requestId, long songCode, string lyricUrl, MusicContentCenterStatusCode errorCode);

        public abstract void OnSongSimpleInfoResult (string requestId, long songCode, string simpleInfo, MusicContentCenterStatusCode errorCode);

        public abstract void OnPreLoadEvent (string requestId, long songCode, int percent, string lyricUrl, PreloadStatusCode status, MusicContentCenterStatusCode errorCode);

    }
}