#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc
{
    ///
    /// @ignore
    ///
    public abstract class IVideoEffectObject
    {
        public abstract int GetObjectId();

        ///
        /// @ignore
        ///
        public abstract int AddOrUpdateVideoEffect(uint nodeId, string templateName);

        ///
        /// @ignore
        ///
        public abstract int RemoveVideoEffect(uint nodeId);

        ///
        /// @ignore
        ///
        public abstract int PerformVideoEffectAction(uint nodeId, VIDEO_EFFECT_ACTION actionId);

        ///
        /// @ignore
        ///
        public abstract int SetVideoEffectFloatParam(string option, string key, float param);

        ///
        /// @ignore
        ///
        public abstract int SetVideoEffectIntParam(string option, string key, int param);

        ///
        /// @ignore
        ///
        public abstract int SetVideoEffectBoolParam(string option, string key, bool param);

        ///
        /// @ignore
        ///
        public abstract float GetVideoEffectFloatParam(string option, string key);

        ///
        /// @ignore
        ///
        public abstract int GetVideoEffectIntParam(string option, string key);

        ///
        /// @ignore
        ///
        public abstract bool GetVideoEffectBoolParam(string option, string key);

    }
}