#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC
#define AGORA_RTM
using System;
using view_t = System.UInt64;

namespace Agora.Rtc
{
    ///
    /// @ignore
    ///
    public abstract class IVideoFrameMetaInfo
    {
        ///
        /// @ignore
        ///
        public abstract string GetMetaInfoStr(META_INFO_KEY key);

    }
}